version: '3.4'

services:
  web:
    image: web
    build:
      context: .
      dockerfile: ./Dockerfile      
    command: sh -c "python manage.py makemigrations &&
                    python manage.py migrate &&
                    python create_data.py &&
                    python manage.py collectstatic --clear --noinput &&
                    python manage.py loaddata sample.json &&
                    gunicorn immobilier.wsgi:application --bind 0.0.0.0:8000"
    env_file: .env-docker
    ports:
      - 8000:8000
    volumes:
      - .:/app
      - static_volume:/app/immobilier/staticfiles
    depends_on: 
      - db
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment: 
      - POSTGRES_USER=user1
      - POSTGRES_PASSWORD=user1
      - POSTGRES_DB=projet_immo
    ports:
      - 5432:5432

volumes:
  postgres_data:
  static_volume: