version: '3.4'

services:
  web:
    image: web
    build:
      context: .
      dockerfile: ./Dockerfile      
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      - DJANGO_SETTINGS_MODULE=immobilier.settings.production
    ports:
      - 8000:8000
    depends_on: 
      - db
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment: 
      - POSTGRES_USER=user1
      - POSTGRES_PASSWORD=user1
      - POSTGRES_DB=projet_immo
    ports:
      - 5432:5432

volumes:
  postgres_data: