# Generated by Django 3.1.6 on 2021-02-04 19:56

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjetImmobilier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('actif', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Appartement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surface', models.FloatField()),
                ('prix', models.FloatField()),
                ('nb_piece', models.IntegerField()),
                ('characteristiques', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=None)),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='immoapp.projetimmobilier')),
            ],
        ),
    ]
