# Generated by Django 3.1.6 on 2021-02-04 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('immoapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caracteristique',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='appartement',
            name='characteristiques',
        ),
        migrations.AlterField(
            model_name='appartement',
            name='projet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appartements', to='immoapp.projetimmobilier'),
        ),
        migrations.AlterField(
            model_name='projetimmobilier',
            name='actif',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='projetimmobilier',
            name='nom',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='appartement',
            name='characteristiques',
            field=models.ManyToManyField(to='immoapp.Caracteristique'),
        ),
    ]
